Return the ignored error
beltran/gosasl pull request #18
Opened 2020-05-12 15:36 UTC by EugeneChung

The error from c.InitSecContext is ignored.

2020-05-12 16:42 UTC, beltran requested changes
This seems to make to make the test TestGSSAPIMechanism in sasl_gssapi_test.go fail, can you just remove the lines that are making this fail from there?
Those would be:
```
for _, input := range [][]byte{[]byte("Ahjdskahdjkaw12kadlsj"), []byte("0"), nil} {
        client.Step(input)
}
```

2020-05-12 16:42 UTC, beltran commented on gssapi.go
> +	return err
Instead of returning err here can you add 
```
if err != nil {
    return err
}
```
before `c.token`

2020-05-13 00:54 UTC, EugeneChung commented
> This seems to make to make the test TestGSSAPIMechanism in sasl_gssapi_test.go fail, can you just remove the lines that are making this fail from there?
> Those would be:
> 
> ```
> for _, input := range [][]byte{[]byte("Ahjdskahdjkaw12kadlsj"), []byte("0"), nil} {
>         client.Step(input)
> }
> ```

```
	} else if m.negotiationStage == 1 {
		err := initClientContext(m.context, m.service+"/"+m.host, challenge)
		if err != nil {
			log.Fatal(err)
			return nil, err
		}
```
of gssapi.go makes it fail. I get it.

2020-05-13 01:55 UTC, beltran commented
Thank you for your contribution!

2020-05-13 01:57 UTC, beltran approved these changes

2020-05-13 01:57 UTC, merged